services:
  elevation:
    image: racemap/elevation-service:v2.0.5
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    cpus: "${CPUS_LIMIT}"
    mem_limit: ${MEMORY_LIMIT}
    depends_on:
      - nginx-proxy
      - jaeger
    volumes:
      - ${TILE_SET_PATH}:/app/data
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}
      TILE_SET_CACHE: ${TILE_SET_CACHE}
      MAX_POST_SIZE: ${MAX_POST_SIZE}
      MAX_PARALLEL_PROCESSING: ${MAX_PARALLEL_PROCESSING}
      PORT: 3000
      BIND: 0.0.0.0
      RUST_LOG: ${LOG_LEVEL:-info}
      OTEL_SERVICE_NAME: elevation-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
    expose:
      - '3000'

  jaeger:
    image: jaegertracing/all-in-one:1.58
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger gRPC
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
    profiles:
      - development
      - telemetry

  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.7.1
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    environment:
      TRUST_DOWNSTREAM_PROXY: false
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
    profiles:
      - production

  acme-companion:
    image: nginxproxy/acme-companion:2.6.0
    container_name: nginx-proxy-acme
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    environment:
      DEFAULT_EMAIL: ${EMAIL}
      ACME_CHALLENGE: DNS-01
      NGINX_PROXY_CONTAINER: nginx-proxy
      ACMESH_DNS_API_CONFIG: |-
        DNS_API: dns_cf
        CF_Key: ${CF_API_KEY}
        CF_Email: ${CF_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    profiles:
      - production

volumes:
  certs:
  acme:
  html:
