services:
  elevation-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - TILE_SET_PATH=/app/data
      - TILE_SET_CACHE=128
      - MAX_POST_SIZE=700kb
      - MAX_PARALLEL_PROCESSING=500
      - PORT=3000
      - BIND=0.0.0.0
      - RUST_LOG=info
      - OTEL_SERVICE_NAME=elevation-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    volumes:
      - ./test_files:/app/data
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.58
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger gRPC  
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver